from charset_normalizer import constant
import requests
import json
import os
import sqlite3
from bs4 import BeautifulSoup
from fastapi import FastAPI, HTTPException
from db import execute_query, fetch_query, init_db, fetch_one

app = FastAPI()

@app.get("/init")
def get_cookies():
    url = "https://bimasislam.kemenag.go.id/jadwalshalat"
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
    }
    
    os.makedirs("data", exist_ok=True)
    
    init_db()
    
    try:
        # Create a session to persist cookies
        session = requests.Session()
        response = session.get(url, headers=headers)
        
        cookies_dict = {}
        # Check if cookies were set
        if response.cookies:
            cookies_dict = session.cookies.get_dict()
            print(f"Generated Cookies: {json.dumps(cookies_dict, indent=4)}")
            
            # Save cookies to a JSON file
            with open("data/cookies.json", "w") as f:
                json.dump(cookies_dict, f, indent=4)
            print("Cookies saved to data/cookies.json")
            
            # Save cookies to SQLite
            for k, v in cookies_dict.items():
                execute_query('INSERT OR REPLACE INTO cookies (name, value) VALUES (?, ?)', (k, v))
        else:
            print("No cookies were generated by the server.")
            
        # Make a second request using the session to get the fully populated HTML
        response = session.get(url, headers=headers)
        
        # Parse HTML to extract province options
        soup = BeautifulSoup(response.text, 'html.parser')
        prov_select = soup.find('select', id='search_prov')
        provinces = []
        if prov_select:
            for option in prov_select.find_all('option'):
                val = option.get('value')
                text = option.text.strip()
                if val:  # Skip empty values like "Pilih Provinsi"
                    provinces.append({"value": val, "text": text})
            
            with open("data/provinces.json", "w") as f:
                json.dump(provinces, f, indent=4)
            print(f"Saved {len(provinces)} provinces to data/provinces.json")
            
            # Save provinces to SQLite
            for prov in provinces:
                # remove spaces, dots, and comma in name_slug
                name_slug = prov["text"].replace(" ", "").replace(".", "").replace(",", "") 
                execute_query('INSERT OR REPLACE INTO provinces (value, name, name_slug) VALUES (?, ?, ?)', (prov["value"], prov["text"], name_slug))
        else:
            print("Select element with id 'search_prov' not found.")
            
        return {
            "message": "Initialization successful",
            "cookies": cookies_dict,
            "provinces": provinces
        }
            
    except requests.exceptions.RequestException as e:
        print(f"Error accessing the website: {e}")
        raise HTTPException(status_code=500, detail=f"Error accessing the website: {str(e)}")

@app.get("/kabupaten-kota")
def get_kabupaten_kota(province: str):
    api_url = 'https://bimasislam.kemenag.go.id/ajax/getKabkoshalat'
    # method = 'POST'
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
    }
    
    # convert province string to mapped value, use LIKE instead of =
    prov_val = fetch_one('SELECT value FROM provinces WHERE UPPER(name) LIKE ?', ('%' + province.upper() + '%',))
    if not prov_val:
        raise HTTPException(status_code=404, detail=f"Province {province} not found")
    prov_val = prov_val[0]

    print(f"Province {province} mapped to {prov_val}")
    # get cookies from db
    cookies_list = fetch_query('SELECT name, value FROM cookies')
    cookies = {cookie[0]: cookie[1] for cookie in cookies_list}
    print(f"Using Cookies: {json.dumps(cookies, indent=4)}")
    
    response = requests.post(api_url, headers=headers, data={'prov': prov_val}, cookies=cookies)
    if response.status_code != 200:
        raise HTTPException(status_code=response.status_code, detail=f"Error accessing the website: {response.status_code}")

    # print response and save data to json file
    print(f"Response: {json.dumps(response.text, indent=4)}") 
    os.makedirs("data/kabupaten-kota", exist_ok=True)
    with open(f"data/kabupaten-kota/{prov_val}.json", "w") as f:
        f.write(response.text)
    
    print(f"Saved {prov_val} to data/kabupaten-kota/{prov_val}.json")
    return response.text
    

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
