"""HTTP scraping and HTML-parsing functions for the Bimas Islam website."""

import logging

import requests
from bs4 import BeautifulSoup

from config import BASE_URL, DEFAULT_HEADERS, KABKOTA_URL, JADWAL_URL

logger = logging.getLogger(__name__)


def fetch_cookies_and_provinces(
    session: requests.Session | None = None,
) -> tuple[dict[str, str], list[dict[str, str]]]:
    """Perform the two-request handshake to obtain cookies and province list.

    Returns:
        A tuple of ``(cookies_dict, provinces_list)`` where *provinces_list*
        contains dicts with ``"value"`` and ``"text"`` keys.
    """
    if session is None:
        session = requests.Session()

    # First request — grab session cookies
    response = session.get(BASE_URL, headers=DEFAULT_HEADERS)
    cookies_dict: dict[str, str] = {}
    if response.cookies:
        cookies_dict = session.cookies.get_dict()
        logger.info("Generated %d cookie(s)", len(cookies_dict))
    else:
        logger.warning("No cookies were generated by the server.")

    # Second request — page is now fully populated with province <select>
    response = session.get(BASE_URL, headers=DEFAULT_HEADERS)

    soup = BeautifulSoup(response.text, "html.parser")
    prov_select = soup.find("select", id="search_prov")
    provinces: list[dict[str, str]] = []
    if prov_select:
        for option in prov_select.find_all("option"):
            val = option.get("value")
            text = option.text.strip()
            if val:  # skip placeholder like "Pilih Provinsi"
                provinces.append({"value": val, "text": text})
        logger.info("Parsed %d province(s) from HTML", len(provinces))
    else:
        logger.warning("Select element with id 'search_prov' not found.")

    return cookies_dict, provinces


def fetch_kabupaten_kota(
    prov_val: str, cookies: dict[str, str]
) -> list[dict[str, str]]:
    """Fetch the list of kabupaten/kota for a given province value.

    Returns:
        A list of dicts with ``"value"`` and ``"name"`` keys.
    """
    headers = {**DEFAULT_HEADERS, "Content-Type": "application/x-www-form-urlencoded"}
    response = requests.post(
        KABKOTA_URL, headers=headers, data={"x": prov_val}, cookies=cookies
    )
    response.raise_for_status()

    soup = BeautifulSoup(response.text, "html.parser")
    result: list[dict[str, str]] = []
    for option in soup.find_all("option"):
        value = option.get("value")
        text = option.text.strip()
        if value:
            result.append({"value": value, "name": text})
    return result


def fetch_jadwal_sholat(
    prov_val: str,
    kab_val: str,
    bulan: str,
    tahun: str,
    cookies: dict[str, str],
) -> dict:
    """Fetch the monthly prayer schedule for a given location.

    Returns:
        The JSON response from the Bimas Islam API.
    """
    headers = {**DEFAULT_HEADERS, "Content-Type": "application/x-www-form-urlencoded"}
    response = requests.post(
        JADWAL_URL,
        headers=headers,
        data={"x": prov_val, "y": kab_val, "bln": bulan, "thn": tahun},
        cookies=cookies,
    )
    response.raise_for_status()
    return response.json()
